Repository linkarchive/Back-End, pull requests merged in 2023-07, with the labels that each got.

#165 fix: s3 key값 추출해서 서비스로 넘겨주기
  src/main/java/project/linkarchive/backend/s3/S3Uploader.java
  src/main/java/project/linkarchive/backend/user/service/UserApiService.java
Labels: refactoring

#166 유저 DTO 테스트 코드 리팩토링
  src/test/java/project/linkarchive/backend/user/domain/UserTest.java
  src/test/java/project/linkarchive/backend/user/request/UpdateNicknameRequestTest.java
  src/test/java/project/linkarchive/backend/user/request/UpdateProfileRequestTest.java
  src/test/java/project/linkarchive/backend/user/response/ProfileResponseTest.java
  src/test/java/project/linkarchive/backend/user/response/UpdateNicknameResponseTest.java
  src/test/java/project/linkarchive/backend/user/response/UpdateProfileResponseTest.java
  src/test/java/project/linkarchive/backend/util/setUpData/SetUpData.java
  src/test/java/project/linkarchive/backend/util/setUpData/UserSetUpData.java
Labels: feat, cleanup, test

#174 링크 삭제 API , 링크 상태 Status 값 추가
  src/main/java/project/linkarchive/backend/advice/success/SuccessCodeConst.java
  src/main/java/project/linkarchive/backend/link/controller/LinkApiController.java
  src/main/java/project/linkarchive/backend/link/domain/Link.java
  src/main/java/project/linkarchive/backend/link/enums/LinkStatus.java
  src/main/java/project/linkarchive/backend/link/repository/LinkRepository.java
  src/main/java/project/linkarchive/backend/link/service/LinkApiService.java
Labels: chore, feat

#175 link 관련 query 조회 시 링크 상태 & 업데이트 시간 Response 필드 추가
  src/main/java/project/linkarchive/backend/bookmark/repository/BookMarkRepositoryImpl.java
  src/main/java/project/linkarchive/backend/bookmark/response/UserMarkResponse.java
  src/main/java/project/linkarchive/backend/link/repository/LinkRepositoryImpl.java
  src/main/java/project/linkarchive/backend/link/response/linkList/LinkResponse.java
  src/main/java/project/linkarchive/backend/link/response/linkList/UserLinkResponse.java
  src/main/java/project/linkarchive/backend/link/response/linkarchive/ArchiveResponse.java
  src/main/java/project/linkarchive/backend/link/response/linkarchive/UserArchiveResponse.java
  src/test/java/project/linkarchive/backend/util/constant/Constants.java
  src/test/java/project/linkarchive/backend/util/setUpData/LinkSetUpData.java
Labels: feat

#177 태그 조회 요청값 id -> nickname으로 변경 및 인덱싱 부여
  src/main/java/project/linkarchive/backend/hashtag/controller/HashTagQueryController.java
  src/main/java/project/linkarchive/backend/hashtag/repository/UserHashTagRepositoryImpl.java
  src/main/java/project/linkarchive/backend/hashtag/service/HashTagQueryService.java
  src/main/java/project/linkarchive/backend/user/domain/User.java
Labels: feat, refactoring

#179 fix: handling null exceptions when registering tags
  src/main/java/project/linkarchive/backend/hashtag/service/HashTagApiService.java
Labels: feat

#181 토큰 유무에 관한 API 분기점을 통합했어요
  src/main/java/project/linkarchive/backend/bookmark/controller/BookMarkQueryController.java
  src/main/java/project/linkarchive/backend/bookmark/service/BookMarkQueryService.java
  src/main/java/project/linkarchive/backend/config/SecurityConfig.java
  src/main/java/project/linkarchive/backend/link/controller/LinkQueryController.java
  src/main/java/project/linkarchive/backend/link/service/LinkQueryService.java
Labels: feat, refactoring, cleanup

#182 링크 삭제 후 삭제 보관함을 조회하는 기능이에요
  src/main/java/project/linkarchive/backend/bookmark/service/BookMarkQueryService.java
  src/main/java/project/linkarchive/backend/link/controller/LinkQueryController.java
  src/main/java/project/linkarchive/backend/link/repository/LinkRepositoryImpl.java
  src/main/java/project/linkarchive/backend/link/response/trash/TrashLinkListResponse.java
  src/main/java/project/linkarchive/backend/link/response/trash/TrashLinkResponse.java
  src/main/java/project/linkarchive/backend/link/response/trash/UserTrashLinkListResponse.java
  src/main/java/project/linkarchive/backend/link/service/LinkQueryService.java
Labels: feat

#184 fix: id return as null when looking up hashtags
  src/main/java/project/linkarchive/backend/bookmark/response/UserMarkResponse.java
  src/main/java/project/linkarchive/backend/bookmark/service/BookMarkQueryService.java
  src/main/java/project/linkarchive/backend/hashtag/response/TagResponse.java
  src/main/java/project/linkarchive/backend/link/service/LinkQueryService.java
Labels: feat, fix

#185 링크 생성 시 태그 등록에 대한 로직 수정 [유저가 자주 사용하는 해시태그]
  src/main/java/project/linkarchive/backend/advice/data/DataConstants.java
  src/main/java/project/linkarchive/backend/config/SecurityConfig.java
  src/main/java/project/linkarchive/backend/hashtag/domain/UserHashTag.java
  src/main/java/project/linkarchive/backend/hashtag/service/HashTagApiService.java
  src/main/java/project/linkarchive/backend/link/service/LinkApiService.java
  src/test/java/project/linkarchive/backend/hashtag/domain/UserHashTagTest.java
  src/test/java/project/linkarchive/backend/util/setUpData/LinkSetUpData.java
Labels: feat, refactoring

#186 사용자별 링크 리스트에 사용된 태그 조회
  src/main/java/project/linkarchive/backend/link/controller/LinkQueryController.java
  src/main/java/project/linkarchive/backend/link/repository/LinkRepository.java
  src/main/java/project/linkarchive/backend/link/service/LinkApiService.java
  src/main/java/project/linkarchive/backend/link/service/LinkQueryService.java
Labels: feat

#187 테스트 코드 - 유저 관련 상수 및 셋팅 / Domain, Repository, Api Service
  README.md
  src/main/java/project/linkarchive/backend/auth/service/OAuthService.java
  src/main/java/project/linkarchive/backend/profileImage/domain/ProfileImage.java
  src/main/java/project/linkarchive/backend/user/controller/UserApiController.java
  src/main/java/project/linkarchive/backend/user/domain/User.java
  src/main/java/project/linkarchive/backend/user/service/UserApiService.java
  src/test/java/project/linkarchive/backend/profileImage/domain/ProfileImageTest.java
  src/test/java/project/linkarchive/backend/user/domain/UserTest.java
  src/test/java/project/linkarchive/backend/user/repository/UserRepositoryTest.java
  src/test/java/project/linkarchive/backend/user/response/ProfileResponseTest.java
  src/test/java/project/linkarchive/backend/user/service/UserApiServiceTest.java
  src/test/java/project/linkarchive/backend/util/constant/Constants.java
  src/test/java/project/linkarchive/backend/util/repository/UserSetUpRepository.java
  src/test/java/project/linkarchive/backend/util/service/UserSetUpService.java
  src/test/java/project/linkarchive/backend/util/setUpData/ProfileImageSetUpData.java
  src/test/java/project/linkarchive/backend/util/setUpData/SetUpData.java
  src/test/java/project/linkarchive/backend/util/setUpData/UserSetUpData.java
Labels: test

#188 Feat/follow user
  src/main/java/project/linkarchive/backend/advice/data/DataConstants.java
  src/main/java/project/linkarchive/backend/advice/exception/ExceptionCodeConst.java
  src/main/java/project/linkarchive/backend/advice/success/SuccessCodeConst.java
  src/main/java/project/linkarchive/backend/relationship/controller/RelationApiController.java
  src/main/java/project/linkarchive/backend/relationship/controller/RelationshipQueryController.java
  src/main/java/project/linkarchive/backend/relationship/domain/Relationship.java
  src/main/java/project/linkarchive/backend/relationship/repository/RelationshipRepository.java
  src/main/java/project/linkarchive/backend/relationship/service/RelationshipApiService.java
  src/main/java/project/linkarchive/backend/relationship/service/RelationshipQueryService.java
  src/main/java/project/linkarchive/backend/user/domain/User.java
  src/main/java/project/linkarchive/backend/user/repository/UserRepository.java
  src/main/java/project/linkarchive/backend/user/response/ProfileResponse.java
  src/main/java/project/linkarchive/backend/user/service/UserApiService.java
Labels: feat

#189 User Test Code / SetUpData
  src/test/java/project/linkarchive/backend/user/domain/UserTest.java
  src/test/java/project/linkarchive/backend/user/repository/UserRepositoryTest.java
  src/test/java/project/linkarchive/backend/user/request/UpdateNicknameRequestTest.java
  src/test/java/project/linkarchive/backend/user/request/UpdateProfileRequestTest.java
  src/test/java/project/linkarchive/backend/user/response/ProfileResponseTest.java
  src/test/java/project/linkarchive/backend/user/response/UpdateNicknameResponseTest.java
  src/test/java/project/linkarchive/backend/user/response/UpdateProfileResponseTest.java
  src/test/java/project/linkarchive/backend/util/repository/UserSetUpRepository.java
  src/test/java/project/linkarchive/backend/util/service/UserSetUpService.java
  src/test/java/project/linkarchive/backend/util/setUpData/BookMarkSetUpData.java
  src/test/java/project/linkarchive/backend/util/setUpData/HashTagSetUpData.java
  src/test/java/project/linkarchive/backend/util/setUpData/LinkSetUpData.java
  src/test/java/project/linkarchive/backend/util/setUpData/MockDataGenerator.java
  src/test/java/project/linkarchive/backend/util/setUpData/ProfileImageSetUpData.java
  src/test/java/project/linkarchive/backend/util/setUpData/SetUpMockData.java
  src/test/java/project/linkarchive/backend/util/setUpData/UserHashTagSetUpData.java
Labels: test

#192 Fix/user link list
  src/main/java/project/linkarchive/backend/config/SecurityConfig.java
  src/main/java/project/linkarchive/backend/link/controller/LinkQueryController.java
Labels: fix

#193 Feat/follow list
  src/main/java/project/linkarchive/backend/relationship/Enum/FollowStatus.java
  src/main/java/project/linkarchive/backend/relationship/controller/RelationshipQueryController.java
  src/main/java/project/linkarchive/backend/relationship/domain/Relationship.java
  src/main/java/project/linkarchive/backend/relationship/repository/RelationshipRepository.java
  src/main/java/project/linkarchive/backend/relationship/response/FollowResponse.java
  src/main/java/project/linkarchive/backend/relationship/service/RelationshipQueryService.java
  src/main/java/project/linkarchive/backend/user/service/UserQueryService.java
Labels: feat

#195 User/ProfileImage 연관관계 역전 및 Query Service Test Code 작성
  src/main/java/project/linkarchive/backend/auth/service/OAuthService.java
  src/main/java/project/linkarchive/backend/link/domain/Link.java
  src/main/java/project/linkarchive/backend/profileImage/domain/ProfileImage.java
  src/main/java/project/linkarchive/backend/user/domain/User.java
  src/test/java/project/linkarchive/backend/profileImage/domain/ProfileImageTest.java
  src/test/java/project/linkarchive/backend/user/domain/UserTest.java
  src/test/java/project/linkarchive/backend/user/service/UserApiServiceTest.java
  src/test/java/project/linkarchive/backend/user/service/UserQueryServiceTest.java
  src/test/java/project/linkarchive/backend/util/constant/Constants.java
  src/test/java/project/linkarchive/backend/util/service/UserSetUpService.java
  src/test/java/project/linkarchive/backend/util/setUpData/ProfileImageSetUpData.java
  src/test/java/project/linkarchive/backend/util/setUpData/SetUpMockData.java
Labels: refactoring, test
