Repository linkarchive/Back-End, pull requests merged in 2023-08, with the labels that each got.

#198 fix: 프로필 조회 시 팔로우 여부 추가
  src/main/java/project/linkarchive/backend/user/controller/UserQueryController.java
  src/main/java/project/linkarchive/backend/user/response/MyProfileResponse.java
  src/main/java/project/linkarchive/backend/user/response/UserProfileResponse.java
  src/main/java/project/linkarchive/backend/user/service/UserQueryService.java
  src/test/java/project/linkarchive/backend/user/response/MyProfileResponseTest.java
  src/test/java/project/linkarchive/backend/user/response/UpdateMyProfileResponseTest.java
  src/test/java/project/linkarchive/backend/user/service/UserQueryServiceTest.java
  src/test/java/project/linkarchive/backend/util/setUpData/MockDataGenerator.java
  src/test/java/project/linkarchive/backend/util/setUpData/SetUpMockData.java
Labels: feat, refactoring

#199 fix: 팔로우, 팔로잉 리스트 조회
  src/main/java/project/linkarchive/backend/relationship/service/RelationshipQueryService.java
Labels: fix, refactoring

#200 운영 서버 배포 테스트입니다.
  .github/workflows/gradle.yml
  src/main/java/project/linkarchive/backend/auth/service/OAuthService.java
  src/main/java/project/linkarchive/backend/config/SecurityConfig.java
  src/main/java/project/linkarchive/backend/isLinkRead/service/IsLinkReadApiService.java
  src/main/java/project/linkarchive/backend/link/controller/LinkQueryController.java
  src/main/java/project/linkarchive/backend/link/domain/Link.java
  src/main/java/project/linkarchive/backend/profileImage/domain/ProfileImage.java
  src/main/java/project/linkarchive/backend/profileImage/repository/ProfileImageRepository.java
  src/main/java/project/linkarchive/backend/relationship/controller/RelationshipApiController.java
  src/main/java/project/linkarchive/backend/relationship/controller/RelationshipQueryController.java
  src/main/java/project/linkarchive/backend/relationship/domain/Relationship.java
  src/main/java/project/linkarchive/backend/relationship/repository/RelationshipRepository.java
  src/main/java/project/linkarchive/backend/relationship/response/FollowResponse.java
  src/main/java/project/linkarchive/backend/relationship/service/RelationshipQueryService.java
  src/main/java/project/linkarchive/backend/s3/S3Uploader.java
  src/main/java/project/linkarchive/backend/user/controller/UserQueryController.java
  src/main/java/project/linkarchive/backend/user/domain/User.java
  src/main/java/project/linkarchive/backend/user/response/MyProfileResponse.java
  src/main/java/project/linkarchive/backend/user/response/UserProfileResponse.java
  src/main/java/project/linkarchive/backend/user/service/UserApiService.java
  src/main/java/project/linkarchive/backend/user/service/UserQueryService.java
  src/test/java/project/linkarchive/backend/profileImage/domain/ProfileImageTest.java
  src/test/java/project/linkarchive/backend/user/domain/UserTest.java
  src/test/java/project/linkarchive/backend/user/response/MyProfileResponseTest.java
  src/test/java/project/linkarchive/backend/user/response/UpdateMyProfileResponseTest.java
  src/test/java/project/linkarchive/backend/user/service/UserApiServiceTest.java
  src/test/java/project/linkarchive/backend/user/service/UserQueryServiceTest.java
  src/test/java/project/linkarchive/backend/util/constant/Constants.java
  src/test/java/project/linkarchive/backend/util/service/UserSetUpService.java
  src/test/java/project/linkarchive/backend/util/setUpData/MockDataGenerator.java
  src/test/java/project/linkarchive/backend/util/setUpData/ProfileImageSetUpData.java
  src/test/java/project/linkarchive/backend/util/setUpData/SetUpMockData.java
Labels: chore

#201 운영 서버 배포 테스트 하겠습니다.
  src/main/java/project/linkarchive/backend/relationship/controller/RelationshipQueryController.java
  src/main/java/project/linkarchive/backend/relationship/response/FollowListResponse.java
  src/main/java/project/linkarchive/backend/relationship/service/RelationshipQueryService.java
Labels: chore

#206 카카오 로그인 이슈로 인한 운영 서버 배포 테스트 중입니다
  .github/workflows/gradle.yml
  .github/workflows/main.yml
  src/main/java/project/linkarchive/backend/relationship/response/FollowResponse.java
  src/main/java/project/linkarchive/backend/relationship/service/RelationshipQueryService.java
Labels: chore

#207 Fix/refresh token issue
  src/main/java/project/linkarchive/backend/auth/controller/OAuthController.java
  src/main/java/project/linkarchive/backend/auth/response/AccessTokenResponse.java
  src/main/java/project/linkarchive/backend/auth/response/RefreshTokenResponse.java
  src/main/java/project/linkarchive/backend/auth/service/OAuthService.java
  src/main/java/project/linkarchive/backend/util/JwtUtil.java
Labels: feat, refactoring

#210 user 관련 API 에서 Request 값을 변경하였습니다.
  src/main/java/project/linkarchive/backend/DataInit.java
  src/main/java/project/linkarchive/backend/advice/data/DataConstants.java
  src/main/java/project/linkarchive/backend/bookmark/controller/BookMarkQueryController.java
  src/main/java/project/linkarchive/backend/bookmark/repository/BookMarkRepositoryImpl.java
  src/main/java/project/linkarchive/backend/bookmark/service/BookMarkQueryService.java
  src/main/java/project/linkarchive/backend/hashtag/controller/HashTagQueryController.java
  src/main/java/project/linkarchive/backend/hashtag/repository/UserHashTagRepositoryImpl.java
  src/main/java/project/linkarchive/backend/hashtag/service/HashTagQueryService.java
  src/main/java/project/linkarchive/backend/link/controller/LinkQueryController.java
  src/main/java/project/linkarchive/backend/link/repository/LinkRepositoryImpl.java
  src/main/java/project/linkarchive/backend/link/service/LinkApiService.java
  src/main/java/project/linkarchive/backend/link/service/LinkQueryService.java
  src/main/java/project/linkarchive/backend/user/controller/UserQueryController.java
  src/main/java/project/linkarchive/backend/user/service/UserQueryService.java
  src/test/java/project/linkarchive/backend/user/service/UserApiServiceTest.java
  src/test/java/project/linkarchive/backend/user/service/UserQueryServiceTest.java
  src/test/java/project/linkarchive/backend/util/service/UserSetUpService.java
  src/test/java/project/linkarchive/backend/util/setUpData/MockDataGenerator.java
  src/test/java/project/linkarchive/backend/util/setUpData/SetUpMockData.java
Labels: refactoring

#212 Fix/follow list security
  src/main/java/project/linkarchive/backend/config/SecurityConfig.java
  src/main/java/project/linkarchive/backend/relationship/controller/RelationshipApiController.java
  src/main/java/project/linkarchive/backend/relationship/controller/RelationshipQueryController.java
  src/main/java/project/linkarchive/backend/relationship/service/RelationshipQueryService.java
Labels: feat, refactoring

#213 tag 관련 API에서 Request 값을 변경하였습니다.
  src/main/java/project/linkarchive/backend/bookmark/controller/BookMarkQueryController.java
  src/main/java/project/linkarchive/backend/bookmark/repository/BookMarkRepositoryImpl.java
  src/main/java/project/linkarchive/backend/bookmark/service/BookMarkQueryService.java
  src/main/java/project/linkarchive/backend/link/controller/LinkApiController.java
  src/main/java/project/linkarchive/backend/link/controller/LinkQueryController.java
  src/main/java/project/linkarchive/backend/link/repository/LinkRepositoryImpl.java
  src/main/java/project/linkarchive/backend/link/service/LinkQueryService.java
Labels: refactoring

#214 사용자별 작성한 링크 또는 북마크된 링크에 사용된 해시태그 조회
  src/main/java/project/linkarchive/backend/link/domain/Link.java
  src/main/java/project/linkarchive/backend/link/repository/LinkRepository.java
  src/main/java/project/linkarchive/backend/link/service/LinkApiService.java
  src/main/java/project/linkarchive/backend/link/service/LinkQueryService.java
  src/main/java/project/linkarchive/backend/user/domain/User.java
Labels: refactoring

#215 테스트 코드 - 유저 관련 셋팅
  src/main/java/project/linkarchive/backend/DataInit.java
  src/main/java/project/linkarchive/backend/advice/success/SuccessCodeConst.java
  src/main/java/project/linkarchive/backend/auth/controller/OAuthController.java
  src/main/java/project/linkarchive/backend/auth/domain/RefreshToken.java
  src/main/java/project/linkarchive/backend/auth/repository/RefreshTokenRepository.java
  src/main/java/project/linkarchive/backend/auth/request/AccessTokenRequest.java
  src/main/java/project/linkarchive/backend/auth/response/AccessTokenResponse.java
  src/main/java/project/linkarchive/backend/auth/service/OAuthService.java
  src/main/java/project/linkarchive/backend/badword/BadWordList.java
  src/main/java/project/linkarchive/backend/bookmark/domain/BookMark.java
  src/main/java/project/linkarchive/backend/bookmark/service/BookMarkApiService.java
  src/main/java/project/linkarchive/backend/config/WebConfig.java
  src/main/java/project/linkarchive/backend/hashtag/domain/HashTag.java
  src/main/java/project/linkarchive/backend/hashtag/service/HashTagApiService.java
  src/main/java/project/linkarchive/backend/link/service/LinkApiService.java
  src/test/java/project/linkarchive/backend/hashtag/domain/HashTagTest.java
  src/test/java/project/linkarchive/backend/user/controller/UserApiControllerTest.java
  src/test/java/project/linkarchive/backend/user/domain/UserTest.java
  src/test/java/project/linkarchive/backend/user/repository/UserRepositoryTest.java
  src/test/java/project/linkarchive/backend/user/request/UpdateNicknameRequestTest.java
  src/test/java/project/linkarchive/backend/user/request/UpdateProfileRequestTest.java
  src/test/java/project/linkarchive/backend/user/response/MyProfileResponseTest.java
  src/test/java/project/linkarchive/backend/user/response/UpdateMyProfileResponseTest.java
  src/test/java/project/linkarchive/backend/user/response/UpdateNicknameResponseTest.java
  src/test/java/project/linkarchive/backend/user/service/UserApiServiceTest.java
  src/test/java/project/linkarchive/backend/user/service/UserQueryServiceTest.java
  src/test/java/project/linkarchive/backend/util/repository/UserSetUpRepository.java
  src/test/java/project/linkarchive/backend/util/setUpData/SetUpMockData.java
Labels: test

#216 테스트 코드 - 프로필 이미지 도메인 및 Response
  src/test/java/project/linkarchive/backend/profileImage/domain/ProfileImageTest.java
  src/test/java/project/linkarchive/backend/profileImage/repository/ProfileImageRepositoryTest.java
  src/test/java/project/linkarchive/backend/profileImage/response/ProfileImageResponseTest.java
  src/test/java/project/linkarchive/backend/util/repository/ProfileImageSetUpRepository.java
  src/test/java/project/linkarchive/backend/util/setUpData/MockDataGenerator.java
  src/test/java/project/linkarchive/backend/util/setUpData/ProfileImageSetUpData.java
  src/test/java/project/linkarchive/backend/util/setUpData/SetUpMockData.java
Labels: test

#219 feat: 둘러보기 해시태그 리스트
  src/main/java/project/linkarchive/backend/hashtag/controller/HashTagQueryController.java
  src/main/java/project/linkarchive/backend/hashtag/domain/UserHashTag.java
  src/main/java/project/linkarchive/backend/hashtag/repository/HashTagRepository.java
  src/main/java/project/linkarchive/backend/hashtag/response/TagResponse.java
  src/main/java/project/linkarchive/backend/hashtag/service/HashTagQueryService.java
Labels: feat

#221 테스트 코드 - 링크 도메인 및 Request, Response 테스트 코드 구현했어요
  src/main/java/project/linkarchive/backend/link/request/CreateLinkRequest.java
  src/main/java/project/linkarchive/backend/link/service/LinkApiService.java
  src/test/java/project/linkarchive/backend/link/domain/LinkTest.java
  src/test/java/project/linkarchive/backend/link/request/CreateLinkRequestTest.java
  src/test/java/project/linkarchive/backend/link/response/LinkMetaDataResponseTest.java
  src/test/java/project/linkarchive/backend/link/response/linkList/LinkResponseTest.java
  src/test/java/project/linkarchive/backend/link/response/linkList/UserLinkListResponseTest.java
  src/test/java/project/linkarchive/backend/link/response/linkList/UserLinkResponseTest.java
  src/test/java/project/linkarchive/backend/link/response/linkarchive/ArchiveResponseTest.java
  src/test/java/project/linkarchive/backend/link/response/linkarchive/UserArchiveResponseTest.java
  src/test/java/project/linkarchive/backend/link/response/linkarchive/UserLinkArchiveResponseTest.java
  src/test/java/project/linkarchive/backend/link/response/trash/TrashLinkListResponseTest.java
  src/test/java/project/linkarchive/backend/link/response/trash/TrashLinkResponseTest.java
  src/test/java/project/linkarchive/backend/link/response/trash/UserTrashLinkListResponseTest.java
  src/test/java/project/linkarchive/backend/util/setUpData/MockDataGenerator.java
  src/test/java/project/linkarchive/backend/util/setUpData/SetUpMockData.java
Labels: test

#222 테스트 코드 - 유저 도메인, Response, Request 관련 테스트 코드
  src/test/java/project/linkarchive/backend/user/domain/UserTest.java
  src/test/java/project/linkarchive/backend/user/request/UpdateNicknameRequestTest.java
  src/test/java/project/linkarchive/backend/user/request/UpdateProfileRequestTest.java
  src/test/java/project/linkarchive/backend/user/response/MyProfileResponseTest.java
  src/test/java/project/linkarchive/backend/user/response/UpdateMyProfileResponseTest.java
  src/test/java/project/linkarchive/backend/user/response/UpdateNicknameResponseTest.java
  src/test/java/project/linkarchive/backend/user/response/UpdateProfileResponseTest.java
  src/test/java/project/linkarchive/backend/user/response/UserProfileResponseTest.java
  src/test/java/project/linkarchive/backend/util/constant/Constants.java
  src/test/java/project/linkarchive/backend/util/setUpData/MockDataGenerator.java
  src/test/java/project/linkarchive/backend/util/setUpData/SetUpMockData.java
Labels: cleanup, test

#229 링크 삭제 시 내부 구현 로직 리팩토링
  src/main/java/project/linkarchive/backend/advice/exception/ExceptionCodeConst.java
  src/main/java/project/linkarchive/backend/bookmark/repository/BookMarkRepository.java
  src/main/java/project/linkarchive/backend/link/repository/LinkRepository.java
  src/main/java/project/linkarchive/backend/link/service/LinkApiService.java
Labels: feat, refactoring

#233 Relationship - 불필요한 수정시간 컬럼 삭제
  src/main/java/project/linkarchive/backend/relationship/domain/Relationship.java
Labels: feat

#234 삭제된 링크가 북마크되는 이슈 해결
  src/main/java/project/linkarchive/backend/bookmark/controller/BookMarkApiController.java
  src/main/java/project/linkarchive/backend/bookmark/service/BookMarkApiService.java
Labels: feat, fix

#237 삭제된 링크를 복구할 수 있는 기능
  src/main/java/project/linkarchive/backend/advice/exception/ExceptionCodeConst.java
  src/main/java/project/linkarchive/backend/advice/success/SuccessCodeConst.java
  src/main/java/project/linkarchive/backend/link/controller/LinkApiController.java
  src/main/java/project/linkarchive/backend/link/domain/Link.java
  src/main/java/project/linkarchive/backend/link/service/LinkApiService.java
Labels: feat

#238 로깅 인터셉터
  src/main/java/project/linkarchive/backend/config/WebConfig.java
  src/main/java/project/linkarchive/backend/interceptor/LoggingInterceptor.java
Labels: chore, feat

#239 기본 프로필 이미지로 수정하는 기능 추가
  src/main/java/project/linkarchive/backend/interceptor/LoggingInterceptor.java
  src/main/java/project/linkarchive/backend/user/controller/UserApiController.java
  src/main/java/project/linkarchive/backend/user/service/UserApiService.java
Labels: feat

#241 로그인, 프로필 이미지 수정 시 리스폰스
  src/main/java/project/linkarchive/backend/auth/response/LoginResponse.java
  src/main/java/project/linkarchive/backend/auth/service/OAuthService.java
  src/main/java/project/linkarchive/backend/user/service/UserApiService.java
  src/test/java/project/linkarchive/backend/user/service/UserApiServiceTest.java
  src/test/java/project/linkarchive/backend/util/constant/Constants.java
Labels: refactoring

#242 단순 메서드명 변경 분입니다
  src/main/java/project/linkarchive/backend/isLinkRead/domain/IsLinkRead.java
  src/main/java/project/linkarchive/backend/isLinkRead/service/IsLinkReadApiService.java
Labels: feat

#243 리프레쉬 업데이트 관련하여 수정시간 추가
  src/main/java/project/linkarchive/backend/auth/domain/RefreshToken.java
Labels: feat

#244 사용자 별 유저 조회 시 리스폰스 값 추가 [링크 수, 마크 수]
  src/main/java/project/linkarchive/backend/bookmark/service/BookMarkApiService.java
  src/main/java/project/linkarchive/backend/link/service/LinkApiService.java
  src/main/java/project/linkarchive/backend/user/domain/User.java
  src/main/java/project/linkarchive/backend/user/repository/UserRepository.java
  src/main/java/project/linkarchive/backend/user/response/UserProfileResponse.java
  src/test/java/project/linkarchive/backend/user/domain/UserTest.java
  src/test/java/project/linkarchive/backend/util/constant/Constants.java
Labels: feat, refactoring

#245 소셜 로그인 분기처리
  src/main/java/project/linkarchive/backend/advice/data/DataConstants.java
  src/main/java/project/linkarchive/backend/auth/AuthProvider.java
  src/main/java/project/linkarchive/backend/auth/controller/OAuthController.java
  src/main/java/project/linkarchive/backend/auth/service/KakaoLoginService.java
  src/main/java/project/linkarchive/backend/auth/service/LocalLoginService.java
  src/main/java/project/linkarchive/backend/auth/service/OauthService.java
  src/main/java/project/linkarchive/backend/user/domain/User.java
  src/main/java/project/linkarchive/backend/user/response/MyProfileResponse.java
  src/test/java/project/linkarchive/backend/user/domain/UserTest.java
  src/test/java/project/linkarchive/backend/util/setUpData/SetUpMockData.java
Labels: refactoring

#246 프로필 이미지 컬럼명 변경
  src/main/java/project/linkarchive/backend/auth/service/KakaoLoginService.java
  src/main/java/project/linkarchive/backend/auth/service/LocalLoginService.java
  src/main/java/project/linkarchive/backend/link/repository/LinkRepositoryImpl.java
  src/main/java/project/linkarchive/backend/profileImage/domain/ProfileImage.java
  src/main/java/project/linkarchive/backend/relationship/service/RelationshipQueryService.java
  src/main/java/project/linkarchive/backend/user/service/UserApiService.java
  src/main/java/project/linkarchive/backend/user/service/UserQueryService.java
  src/test/java/project/linkarchive/backend/profileImage/domain/ProfileImageTest.java
  src/test/java/project/linkarchive/backend/util/setUpData/SetUpMockData.java
Labels: docs, feat

#248 Fix/security issue
  src/main/java/project/linkarchive/backend/advice/exception/ExceptionCodeConst.java
  src/main/java/project/linkarchive/backend/auth/controller/OAuthController.java
  src/main/java/project/linkarchive/backend/auth/repository/RefreshTokenRepository.java
  src/main/java/project/linkarchive/backend/auth/request/RefreshTokenRequest.java
  src/main/java/project/linkarchive/backend/auth/service/OauthService.java
  src/main/java/project/linkarchive/backend/config/SecurityConfig.java
  src/main/java/project/linkarchive/backend/security/SecurityExceptionHandler.java
  src/main/java/project/linkarchive/backend/security/TokenAuthenticationFilter.java
  src/main/java/project/linkarchive/backend/util/JwtUtil.java
Labels: feat, fix, refactoring

#249 유저 관련 연관 테이블의 영속성 전이를 수정해줬어요
  src/main/java/project/linkarchive/backend/auth/service/KakaoLoginService.java
  src/main/java/project/linkarchive/backend/auth/service/LocalLoginService.java
  src/main/java/project/linkarchive/backend/pin/domain/Pin.java
  src/main/java/project/linkarchive/backend/profileImage/domain/ProfileImage.java
  src/main/java/project/linkarchive/backend/user/domain/User.java
Labels: chore, refactoring

#250 링크 관련 영속성 전이 셋팅
  src/main/java/project/linkarchive/backend/hashtag/domain/Hashtag.java
  src/main/java/project/linkarchive/backend/hashtag/domain/UserHashtag.java
  src/main/java/project/linkarchive/backend/hashtag/service/HashTagApiService.java
  src/main/java/project/linkarchive/backend/link/domain/Link.java
  src/main/java/project/linkarchive/backend/link/domain/LinkHashtag.java
  src/main/java/project/linkarchive/backend/link/service/LinkApiService.java
Labels: chore

#251 스케쥴러 : 삭제된 링크 일괄 삭제 기능
  src/main/java/project/linkarchive/backend/LinkarchiveApplication.java
  src/main/java/project/linkarchive/backend/advice/data/DataConstants.java
  src/main/java/project/linkarchive/backend/aspect/SchedulerExceptionAspect.java
  src/main/java/project/linkarchive/backend/link/repository/LinkRepository.java
  src/main/java/project/linkarchive/backend/link/scheduler/LinkScheduler.java
Labels: feat

#252 fix: login user agent error
  src/main/java/project/linkarchive/backend/advice/exception/ExceptionController.java
  src/main/java/project/linkarchive/backend/auth/domain/RefreshToken.java
  src/main/java/project/linkarchive/backend/user/domain/User.java
Labels: fix
